export const data = [
    { "id": "1",
      "title": "Double Indemnity",
      "year": "1944",
      "director": "Billy Wilder",
      "country": "United States",
      "img": "./multimedia/DoubleIndemnity.jpg",
      "synopsis": "An insurance representative lets himself be talked by a seductive housewife into a murder/insurance fraud scheme that arouses the suspicion of an insurance investigator."
    },
    { "id": "2",
      "title": "Laura",
      "year": "1944",
      "director": "Otto Preminger",
      "country": "United States",
      "img": "./multimedia/Laura.jpg",
      "synopsis": "A police detective falls in love with the woman whose murder he is investigating."
    },
    { "id": "3",
      "title": "Sunset Boulevard",
      "year": "1950",
      "director": "Billy Wilder",
      "country": "United States",
      "img": "./multimedia/SunsetBoulevard.jpg",
      "synopsis": "A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return."
    },
    { "id": "4",
      "title": "The Big Heat",
      "year": "1953",
      "director": "Fritz Lang",
      "country": "United States",
      "img": "./multimedia/TheBigHeat.jpg",
      "synopsis": "Tough cop Dave Bannion takes on a politically powerful crime syndicate."
    },
    { "id": "5",
      "title": "The Lady of Shangai",
      "year": "1947",
      "director": "Billy Wilder",
      "country": "United States",
      "img": "./multimedia/TheLadyfromShangai.jpg",
      "synopsis": "Fascinated by gorgeous Mrs. Bannister, seaman Michael O'Hara joins a bizarre yachting cruise, and ends up mired in a complex murder plot."
    }, 
    { "id": "6",
      "title": "The Maltese Falcon",
      "year": "1941",
      "director": "John Huston",
      "country": "United States",
      "img": "./multimedia/TheMalteseFalcon.jpg",
      "synopsis": "A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette."
    },
    { "id": "7",
      "title": "The Third Man",
      "year": "1949",
      "director": "Carol Reed",
      "country": "United States",
      "img": "./multimedia/TheThirdMan.jpg",
      "synopsis": "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime."
    },
    { "id": "8",
      "title": "Detour",
      "year": "1945",
      "director": "Edgar G. Ulmer",
      "country": "United States",
      "img": "./multimedia/Detour.jpg",
      "synopsis": "Chance events trap hitchhiking nightclub pianist Al Roberts in a tightening net of death, deception and blackmail."
  },
    
]